{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kubernetes-gateway-exporter.fullname" . }}
  labels:
    app: {{ include "kubernetes-gateway-exporter.name" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "kubernetes-gateway-exporter.name" . }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
