replicaCount: 1

image:
  repository: my-registry/kubernetes-gateway-exporter
  pullPolicy: IfNotPresent
  tag: "latest"

serviceAccount:
  create: true
  name: "gateway-exporter-sa"
  annotations: {}

networkPolicy:
  enabled: true

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65532

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

service:
  type: ClusterIP
  port: 8080

config:
  enableOtel: "false"

serviceMonitor:
  enabled: true
  interval: 15s

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi

nodeSelector: {}
tolerations: []
affinity: {}
